import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Eye, Target, Wallet } from "lucide-react";

export default function ValuesSection() {
  return <section className="bg-muted"><div className="mx-auto grid max-w-7xl items-center gap-10 px-6 py-20 lg:grid-cols-2 lg:gap-16 lg:py-24">
    <div><p className="eyebrow">Our values</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-primary sm:text-4xl">Excellence Through Values</h2><p className="mt-4 max-w-xl text-base leading-7 text-muted-foreground">The way we work starts with your requirements. We aim to make each property search clear, thoughtful and useful.</p>
      <div className="mt-7 space-y-3">{[{ title: "Our mission", text: "Help people find spaces that suit their plans, with clear information at every step.", icon: Target }, { title: "Our vision", text: "Make property discovery easier through considered selection and practical guidance.", icon: Eye }].map(({ title, text, icon: Icon }) => <div key={title} className="flex gap-4 rounded-xl border border-border bg-card p-5 shadow-lg shadow-primary/5"><span className="flex size-11 shrink-0 items-center justify-center rounded-full border border-border text-secondary-ink"><Icon size={20} aria-hidden="true" /></span><div><h3 className="text-lg font-semibold text-primary">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></div>)}</div>
    </div>
    <div className="border border-border bg-card p-2.5"><div className="relative aspect-[1/1.05] overflow-hidden"><Image src="/assets/images/amber-residences.svg" alt="Contemporary home at dusk" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /></div></div>
  </div><div className="border-t border-border bg-background"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-6 py-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="flex size-12 shrink-0 items-center justify-center rounded-full bg-primary text-white"><Wallet size={22} aria-hidden="true" /></span><div><h3 className="text-base font-semibold text-primary">Financing conversations</h3><p className="text-sm text-muted-foreground">Discuss your requirements and the documents you may need.</p></div></div><Link href="/loan-assistance" className="inline-flex min-h-11 items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-accent-foreground hover:underline">Learn about loans <ArrowUpRight size={16} /></Link></div></div></section>;
}
